### ISSUE TITLE
Issue installing this 

### ISSUE THREAD

**Issue by sharmaakhil100** [gyrdym/ml_linalg#60]
I added the required version to my dependencies but I get an error when I run "flutter pub get" in my terminal. The error says:

The current Dart SDK version is 2.3.0-dev.0.5.flutter-a1668566e5.               
Because (title_of_my_app) depends on ml_linalg >=10.0.0 which requires SDK version >=2.3.0 <3.0.0, version solving failed.

I already have updated Flutter to the latest version according to Android Studio, so is there something I'm missing here? Thanks

EDIT: If I install a version of this library before 10.0.0, then it works. I just tried installing 9.0.0 and that worked, but if someone could help me figure out why I can't install the latest version that'd be great

**Comment by gyrdym** [comment]
@sharmaakhil100 Thank you for reporting the issue, I will try myself to install the library as a flutter project dependency to find out why the issue takes place.

**Comment by gyrdym** [comment]
@sharmaakhil100 By the way, could you please show me your `pubspec.yaml`?

**Comment by gyrdym** [comment]
@sharmaakhil100 checkout the last update - I decided to change SDK version constraint from `>=2.3.0` to `>=2.2.0`, because there is no usage of any functionality from 2.3.0 in the library. It should work now, just do `flutter pub get` again (you will receive ml_linalg v10.0.4 with updated SDK version constrains)

**Comment by sharmaakhil100** [comment]
Thanks for the update. That solved my issue.
